"use client";

import { useMemo, useState } from "react";
import { CalendarDays, Loader2, Minus, Plus } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { CurrencyPrice } from "@/components/currency/currency-price";

export function ActivityBookingCard({ activityId, price }: { activityId: string; price: number }) {
  const [loading, setLoading] = useState(false); const [done, setDone] = useState(""); const [form, setForm] = useState({ name: "", email: "", mobile: "", activityDate: "", timeSlot: "", adults: 1, children: 0, notes: "" });
  const guests = form.adults + form.children; const total = useMemo(() => price * guests, [price, guests]);
  function count(key: "adults" | "children", delta: number) { setForm((current) => ({ ...current, [key]: Math.max(key === "adults" ? 1 : 0, current[key] + delta) })); }
  async function submit(event: React.FormEvent) { event.preventDefault(); setLoading(true); try { const response = await fetch("/api/activity-bookings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, activityId }) }); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.message || "Booking failed"); setDone(data.data.bookingNumber); toast.success("Activity booking received"); } catch (error) { toast.error((error as Error).message); } finally { setLoading(false); } }
  if (done) return <aside className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6"><h2 className="text-xl font-extrabold text-emerald-900">Booking received</h2><p className="mt-2 text-sm text-emerald-800">Reference: <strong>{done}</strong>. Our team will contact you to confirm availability and payment.</p></aside>;
  return <aside className="rounded-2xl border border-border bg-white p-5 shadow-xl shadow-slate-900/10"><p className="text-sm text-muted-foreground">Starting from</p><p className="mt-1 text-3xl font-extrabold"><CurrencyPrice amount={price} /> <span className="text-sm font-normal text-muted-foreground">/ person</span></p><form onSubmit={submit} className="mt-5 space-y-4"><div><Label className="mb-1.5 block">Activity date</Label><div className="relative"><CalendarDays className="absolute left-3 top-3 size-4 text-muted-foreground" /><Input className="pl-9" type="date" min={new Date().toISOString().slice(0, 10)} value={form.activityDate} onChange={(e) => setForm({ ...form, activityDate: e.target.value })} required /></div></div><div className="grid grid-cols-2 gap-3">{(["adults", "children"] as const).map((key) => <div key={key}><Label className="mb-1.5 block capitalize">{key}</Label><div className="flex items-center justify-between rounded-lg border p-1"><Button type="button" size="icon" variant="ghost" onClick={() => count(key, -1)}><Minus className="size-4" /></Button><strong>{form[key]}</strong><Button type="button" size="icon" variant="ghost" onClick={() => count(key, 1)}><Plus className="size-4" /></Button></div></div>)}</div>{(["name", "email", "mobile"] as const).map((key) => <div key={key}><Label className="mb-1.5 block capitalize">{key}</Label><Input type={key === "email" ? "email" : "text"} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} required /></div>)}<div className="flex items-center justify-between border-t pt-4"><span className="font-semibold">Estimated total</span><strong className="text-xl"><CurrencyPrice amount={total} /></strong></div><Button className="w-full" size="lg" variant="gradient" disabled={loading}>{loading ? <Loader2 className="size-4 animate-spin" /> : null}Book activity</Button><p className="text-center text-xs text-muted-foreground">No payment now. Availability is confirmed by our team.</p></form></aside>;
}
