import Link from "next/link";
import { ActivityBookingStatusSelect } from "@/components/admin/activity-booking-status";
import { Card, CardContent } from "@/components/ui/card";
import { CurrencyPrice } from "@/components/currency/currency-price";
import { listAdminActivityBookings } from "@/lib/dashboard";
import { formatDate } from "@/lib/utils";
import type { ActivityBookingDTO } from "@/types";

export default async function ActivityBookingsPage({ searchParams }: { searchParams: Promise<{ q?: string }> }) { const q = (await searchParams).q?.trim().toLowerCase() ?? ""; const all = await listAdminActivityBookings() as ActivityBookingDTO[]; const rows = q ? all.filter((booking) => `${booking.bookingNumber} ${booking.name} ${booking.email} ${typeof booking.activity === "string" ? "" : booking.activity.title}`.toLowerCase().includes(q)) : all; return <div className="space-y-5"><div><h1 className="text-2xl font-bold">Activity bookings</h1><p className="text-muted-foreground">{all.length} total experience bookings</p></div><form className="max-w-md"><input name="q" defaultValue={q} placeholder="Search booking, guest or activity" className="h-11 w-full rounded-lg border bg-background px-4 text-sm outline-none focus:ring-2 focus:ring-primary" /></form><Card><CardContent className="overflow-x-auto p-0">{rows.length ? <table className="w-full min-w-[1000px] text-sm"><thead><tr className="border-b text-left text-muted-foreground"><th className="p-4">Booking</th><th className="p-4">Activity</th><th className="p-4">Guest</th><th className="p-4">Date</th><th className="p-4">Guests</th><th className="p-4">Amount</th><th className="p-4">Status</th></tr></thead><tbody>{rows.map((booking) => { const activity = typeof booking.activity === "string" ? null : booking.activity; return <tr key={booking._id} className="border-b border-border/50"><td className="p-4 font-bold">{booking.bookingNumber}</td><td className="p-4">{activity ? <Link className="font-semibold text-primary hover:underline" href={`/activities/${activity.slug}`}>{activity.title}</Link> : "—"}<p className="text-xs text-muted-foreground">{activity?.destination}</p></td><td className="p-4"><p className="font-medium">{booking.name}</p><p className="text-xs text-muted-foreground">{booking.mobile}</p></td><td className="p-4">{formatDate(booking.activityDate)}</td><td className="p-4">{booking.totalParticipants}</td><td className="p-4 font-bold"><CurrencyPrice amount={booking.totalAmount} /></td><td className="p-4"><ActivityBookingStatusSelect id={booking._id} status={booking.status} /></td></tr>; })}</tbody></table> : <div className="py-12 text-center text-sm text-muted-foreground">No activity bookings found.</div>}</CardContent></Card></div>; }
