"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useSession } from "next-auth/react";
import { Calendar, Check, FileUp, Loader2, Minus, Plus, ShieldCheck, X } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { formatDate, formatINR, tripDuration } from "@/lib/utils";

interface BookingBoxProps { tripId:string;slug:string;pricePerPerson:number;availableSeats:number;startDate:string;endDate:string;pickupLocation:string;durationDays?:number;country?:string;departureCities?:string[];partnerSlug?:string;customDate?:boolean;visaRequired?:boolean;visaNote?:string;visaDocuments?:string[];visaFee?:number;permitRequired?:boolean;permitNote?:string;permitDocuments?:string[];permitFee?:number }
type UploadedDocument={label:string;fileId:string;fileName:string};
export interface BookingDraft { tripId:string;slug:string;partnerSlug?:string;departureCity:string;travelStartDate:string;travelEndDate:string;adults:number;childrenWithBed:number;childrenWithoutBed:number;infants:number;seats:number;name:string;email:string;mobile:string;pricePerPerson:number;totalAmount:number;visaFee:number;permitFee:number;travelCompliance?:{visa?:{hasDocument:boolean;documents:UploadedDocument[]};permit?:{hasDocument:boolean;documents:UploadedDocument[]}} }

function Counter({label,hint,value,onChange,min=0,max=20}:{label:string;hint:string;value:number;onChange:(value:number)=>void;min?:number;max?:number}){return <div><p className="mb-2 text-sm font-semibold">{label}</p><div className="flex h-12 items-center justify-between rounded-xl border px-2"><button type="button" aria-label={`Reduce ${label}`} onClick={()=>onChange(Math.max(min,value-1))} disabled={value<=min} className="flex size-8 items-center justify-center rounded-lg hover:bg-secondary disabled:opacity-30"><Minus className="size-4"/></button><span className="text-lg font-extrabold">{value}</span><button type="button" aria-label={`Add ${label}`} onClick={()=>onChange(Math.min(max,value+1))} disabled={value>=max} className="flex size-8 items-center justify-center rounded-lg hover:bg-secondary disabled:opacity-30"><Plus className="size-4"/></button></div><p className="mt-1 text-xs text-muted-foreground">{hint}</p></div>}

function ComplianceQuestion({kind,country,note,documents,hasDocument,onAnswer,onFile}:{kind:"visa"|"permit";country:string;note?:string;documents:string[];hasDocument:boolean;onAnswer:(value:boolean)=>void;onFile:(label:string,file?:File)=>void}) {
  const title=kind[0].toUpperCase()+kind.slice(1);
  return <section className="rounded-xl border bg-secondary/20 p-4">
    <div className="flex flex-col gap-3 lg:flex-row lg:items-center ">
      <p className="font-semibold">{title} required: Do you have a {kind} for {country}?</p>
      <div className="flex shrink-0 gap-6"><label className="flex items-center gap-2"><input type="radio" name={`${kind}-answer`} checked={hasDocument} onChange={()=>onAnswer(true)} className="size-4 accent-primary"/>Yes</label><label className="flex items-center gap-2"><input type="radio" name={`${kind}-answer`} checked={!hasDocument} onChange={()=>onAnswer(false)} className="size-4 accent-primary"/>No</label></div>
    </div>
    {!hasDocument&&<div className="mt-4 space-y-3">{note&&<p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">{note}</p>}<p className="text-sm font-medium">Upload the required documents:</p><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{documents.map((document)=><div key={document}><Label className="mb-1 block text-xs">{document} <span className="text-destructive">*</span></Label><Input type="file" accept=".pdf,.jpg,.jpeg,.png" required onChange={(event)=>onFile(document,event.target.files?.[0])}/></div>)}</div><p className="flex items-center gap-1 text-xs text-muted-foreground"><FileUp className="size-3"/>PDF, JPG or PNG · maximum 5 MB each</p></div>}
  </section>;
}

export function BookingBox(props:BookingBoxProps){
  const{data:session}=useSession();const router=useRouter();const[open,setOpen]=useState(false);const[calculated,setCalculated]=useState(false);const[continuing,setContinuing]=useState(false);const[compliance,setCompliance]=useState({visaHasDocument:false,permitHasDocument:false});const[files,setFiles]=useState<Record<string,File>>({});
  const packageDays=tripDuration(props.startDate,props.endDate,props.durationDays).days;const soldOut=!props.customDate&&props.availableSeats<=0;const international=(props.country||"India").trim().toLowerCase()!=="india";const departureCities=props.departureCities?.filter(Boolean)??[];const domesticDeparture=props.pickupLocation?.trim()||"Joining Direct";
  const[form,setForm]=useState({departureCity:international?departureCities[0]||"":domesticDeparture,travelStartDate:props.customDate?"":props.startDate.slice(0,10),adults:1,childrenWithBed:0,childrenWithoutBed:0,infants:0,name:session?.user?.name??"",email:session?.user?.email??"",mobile:"",accepted:false});
  useEffect(()=>{if(open)document.body.style.overflow="hidden";return()=>{document.body.style.overflow=""}},[open]);
  const travelers=form.adults+form.childrenWithBed+form.childrenWithoutBed+form.infants;const maximumTravelers=props.customDate?20:Math.min(20,Math.max(1,props.availableSeats));const counterMaximum=(key:"adults"|"childrenWithBed"|"childrenWithoutBed"|"infants")=>Math.max(key==="adults"?1:0,maximumTravelers-(travelers-form[key]));const visaFee=props.visaRequired&&!compliance.visaHasDocument?Number(props.visaFee||0):0;const permitFee=props.permitRequired&&!compliance.permitHasDocument?Number(props.permitFee||0):0;const total=(props.pricePerPerson+visaFee+permitFee)*travelers;
  const endDate=(()=>{if(!props.customDate)return props.endDate.slice(0,10);if(!form.travelStartDate)return"";const value=new Date(`${form.travelStartDate}T00:00:00.000Z`);value.setUTCDate(value.getUTCDate()+packageDays-1);return value.toISOString().slice(0,10)})();
  function update<K extends keyof typeof form>(key:K,value:(typeof form)[K]){setForm((current)=>({...current,[key]:value}));setCalculated(false)}
  function validate(){if(!form.departureCity.trim())return"Enter your departure city.";if(props.customDate&&!form.travelStartDate)return"Select your date of travel.";if(form.name.trim().length<2)return"Enter the lead traveler name.";if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email))return"Enter a valid email address.";if(!/^[6-9]\d{9}$/.test(form.mobile))return"Enter a valid 10-digit mobile number.";if(props.visaRequired&&!compliance.visaHasDocument&&(props.visaDocuments??[]).some((label)=>!files[`visa:${label}`]))return"Upload all required visa documents.";if(props.permitRequired&&!compliance.permitHasDocument&&(props.permitDocuments??[]).some((label)=>!files[`permit:${label}`]))return"Upload all required permit documents.";if(!form.accepted)return"Accept the booking terms to continue.";if(!props.customDate&&travelers>props.availableSeats)return`Only ${props.availableSeats} seats are available.`;return""}
  async function upload(kind:"visa"|"permit",labels:string[]){return Promise.all(labels.map(async(label)=>{const body=new FormData();body.set("file",files[`${kind}:${label}`]);const response=await fetch("/api/booking-documents",{method:"POST",body});const json=await response.json();if(!response.ok)throw new Error(json.message||`Could not upload ${label}`);return{label,fileId:json.data.fileId as string,fileName:json.data.fileName as string}}))}
  async function continueToReview(){const error=validate();if(error)return toast.error(error);setContinuing(true);try{const travelCompliance:BookingDraft["travelCompliance"]={};if(props.visaRequired)travelCompliance.visa={hasDocument:compliance.visaHasDocument,documents:compliance.visaHasDocument?[]:await upload("visa",props.visaDocuments??[])};if(props.permitRequired)travelCompliance.permit={hasDocument:compliance.permitHasDocument,documents:compliance.permitHasDocument?[]:await upload("permit",props.permitDocuments??[])};const draft:BookingDraft={tripId:props.tripId,slug:props.slug,partnerSlug:props.partnerSlug,departureCity:form.departureCity.trim(),travelStartDate:form.travelStartDate,travelEndDate:endDate,adults:form.adults,childrenWithBed:form.childrenWithBed,childrenWithoutBed:form.childrenWithoutBed,infants:form.infants,seats:travelers,name:form.name.trim(),email:form.email.trim(),mobile:form.mobile,pricePerPerson:props.pricePerPerson,totalAmount:total,visaFee,permitFee,travelCompliance};sessionStorage.setItem("voibee-booking-draft",JSON.stringify(draft));router.push(`/booking-review?package=${encodeURIComponent(props.slug)}`)}catch(uploadError){toast.error(uploadError instanceof Error?uploadError.message:"Document upload failed");setContinuing(false)}}
  return <><div className="sticky top-24 rounded-2xl border border-primary/15 bg-white p-5 shadow-lg shadow-primary/5"><p className="text-sm text-muted-foreground">Starting from</p><p className="mt-1 text-3xl font-extrabold">{formatINR(props.pricePerPerson)} <span className="text-sm font-medium text-muted-foreground">/ person</span></p><p className="mt-3 flex items-center gap-2 text-sm text-muted-foreground"><Calendar className="size-4 text-primary"/>{props.customDate?`${packageDays} days · select your date`:`${formatDate(props.startDate)} – ${formatDate(props.endDate)}`}</p><Button disabled={soldOut} variant="gradient" size="lg" className="mt-5 w-full" onClick={()=>setOpen(true)}>{soldOut?"Sold Out":"Book Now"}</Button><p className="mt-3 flex items-center justify-center gap-1.5 text-xs text-muted-foreground"><ShieldCheck className="size-3.5 text-success"/>Online and offline booking available</p></div>
  {open&&<div className="fixed inset-0 z-[80] flex items-end justify-center bg-slate-950/55 backdrop-blur-sm sm:items-center sm:p-5" role="dialog" aria-modal="true" onMouseDown={(event)=>{if(event.target===event.currentTarget)setOpen(false)}}><div className="max-h-[94vh] w-full max-w-5xl overflow-y-auto rounded-t-3xl bg-white shadow-2xl sm:rounded-3xl"><div className="sticky top-0 z-10 flex items-center justify-between border-b bg-white px-5 py-4 sm:px-7"><div><p className="text-xs font-bold uppercase tracking-wider text-primary">Plan your booking</p><h2 className="text-xl font-extrabold sm:text-2xl">Traveler and trip details</h2></div><button onClick={()=>setOpen(false)} className="flex size-10 items-center justify-center rounded-full bg-secondary"><X/></button></div><div className="space-y-7 p-5 sm:p-7">
    <div className={`grid gap-5 ${props.customDate?"sm:grid-cols-2":"sm:grid-cols-1"}`}><div><Label className="mb-2 block">{international?"Departure city":"Departure"} *</Label>{international?<Select value={form.departureCity} onChange={(event)=>update("departureCity",event.target.value)} className="h-12"><option value="" disabled>Select departure city</option>{departureCities.map((city)=><option key={city}>{city}</option>)}</Select>:<div className="flex h-12 items-center rounded-md border bg-secondary/40 px-3 font-semibold">{domesticDeparture}</div>}</div>{props.customDate&&<div><Label className="mb-2 block">Date of travel *</Label><Input type="date" value={form.travelStartDate} min={new Date().toISOString().slice(0,10)} onChange={(event)=>update("travelStartDate",event.target.value)} className="h-12"/></div>}</div>
    <div className="border-y border-dashed py-6"><h3 className="mb-5 text-lg font-extrabold">Travelers <span className="text-sm font-normal text-muted-foreground">(maximum {maximumTravelers})</span></h3><div className="grid grid-cols-2 gap-4 lg:grid-cols-4"><Counter label="Adult" hint="12+ years" value={form.adults} min={1} max={counterMaximum("adults")} onChange={(value)=>update("adults",value)}/><Counter label="Child (with bed)" hint="Below 12 years" value={form.childrenWithBed} max={counterMaximum("childrenWithBed")} onChange={(value)=>update("childrenWithBed",value)}/><Counter label="Child (without bed)" hint="Below 12 years" value={form.childrenWithoutBed} max={counterMaximum("childrenWithoutBed")} onChange={(value)=>update("childrenWithoutBed",value)}/><Counter label="Infant" hint="0–2 years" value={form.infants} max={counterMaximum("infants")} onChange={(value)=>update("infants",value)}/></div></div>
    <div><h3 className="mb-5 text-lg font-extrabold">Contact details</h3><div className="grid gap-4 sm:grid-cols-3"><div><Label className="mb-2 block">Full name *</Label><Input value={form.name} onChange={(event)=>update("name",event.target.value)} className="h-12"/></div><div><Label className="mb-2 block">Mobile number *</Label><Input inputMode="numeric" maxLength={10} value={form.mobile} onChange={(event)=>update("mobile",event.target.value.replace(/\D/g,""))} className="h-12"/></div><div><Label className="mb-2 block">Email *</Label><Input type="email" value={form.email} onChange={(event)=>update("email",event.target.value)} className="h-12"/></div></div></div>
    {(props.visaRequired||props.permitRequired)&&<div className="space-y-4 border-y border-dashed py-6"><h3 className="text-lg font-extrabold">Travel documents</h3>{props.visaRequired&&<ComplianceQuestion kind="visa" country={props.country||"destination country"} note={props.visaNote} documents={props.visaDocuments??[]} hasDocument={compliance.visaHasDocument} onAnswer={(value)=>setCompliance((current)=>({...current,visaHasDocument:value}))} onFile={(label,file)=>file&&setFiles((current)=>({...current,[`visa:${label}`]:file}))}/>} {props.permitRequired&&<ComplianceQuestion kind="permit" country={props.country||"destination country"} note={props.permitNote} documents={props.permitDocuments??[]} hasDocument={compliance.permitHasDocument} onAnswer={(value)=>setCompliance((current)=>({...current,permitHasDocument:value}))} onFile={(label,file)=>file&&setFiles((current)=>({...current,[`permit:${label}`]:file}))}/>}</div>}
    <label className="flex cursor-pointer items-start gap-3 text-sm"><input type="checkbox" checked={form.accepted} onChange={(event)=>update("accepted",event.target.checked)} className="mt-0.5 size-5 accent-primary"/><span>I accept the <a href="/terms" target="_blank" className="font-semibold text-primary underline">Terms & Conditions</a> and <a href="/privacy" target="_blank" className="font-semibold text-primary underline">Privacy Policy</a>. *</span></label>
    <div className="flex flex-col items-stretch justify-end gap-4 border-t pt-5 sm:flex-row sm:items-center">{!calculated?<Button variant="gradient" size="lg" onClick={()=>{const error=validate();if(error)return toast.error(error);setCalculated(true)}}>Calculate Price</Button>:<><div className="mr-auto rounded-2xl bg-primary/5 px-5 py-3"><p className="text-xs text-muted-foreground">Total for {travelers} traveler(s)</p><p className="text-2xl font-extrabold text-primary">{formatINR(total)}</p></div><Button variant="gradient" size="lg" disabled={continuing} onClick={()=>void continueToReview()}>{continuing?<Loader2 className="animate-spin"/>:<Check/>}Continue</Button></>}</div>
  </div></div></div>}</>;
}
