"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useSession } from "next-auth/react";
import { Calendar, Check, Loader2, Minus, Plus, ShieldCheck, X } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { formatDate, formatINR, tripDuration } from "@/lib/utils";

interface BookingBoxProps { tripId: string; slug: string; pricePerPerson: number; availableSeats: number; startDate: string; endDate: string; pickupLocation: string; durationDays?: number; country?: string; departureCities?: string[]; partnerSlug?: string; customDate?: boolean; }

export interface BookingDraft { tripId: string; slug: string; partnerSlug?: string; departureCity: string; travelStartDate: string; travelEndDate: string; adults: number; childrenWithBed: number; childrenWithoutBed: number; infants: number; seats: number; name: string; email: string; mobile: string; pricePerPerson: number; totalAmount: number; }

function Counter({ label, hint, value, onChange, min = 0, max = 20 }: { label: string; hint: string; value: number; onChange: (value: number) => void; min?: number; max?: number }) {
  return <div><p className="mb-2 text-sm font-semibold">{label}</p><div className="flex h-12 items-center justify-between rounded-xl border border-border px-2"><button type="button" aria-label={`Reduce ${label}`} onClick={() => onChange(Math.max(min, value - 1))} disabled={value <= min} className="flex size-8 items-center justify-center rounded-lg text-muted-foreground hover:bg-secondary disabled:opacity-30"><Minus className="size-4" /></button><span className="text-lg font-extrabold">{value}</span><button type="button" aria-label={`Add ${label}`} onClick={() => onChange(Math.min(max, value + 1))} disabled={value >= max} className="flex size-8 items-center justify-center rounded-lg text-muted-foreground hover:bg-secondary disabled:opacity-30"><Plus className="size-4" /></button></div><p className="mt-1 text-xs text-muted-foreground">{hint}</p></div>;
}

export function BookingBox(props: BookingBoxProps) {
  const { data: session } = useSession();
  const router = useRouter();
  const [open, setOpen] = useState(false);
  const [calculated, setCalculated] = useState(false);
  const [continuing, setContinuing] = useState(false);
  const packageDays = tripDuration(props.startDate, props.endDate, props.durationDays).days;
  const soldOut = !props.customDate && props.availableSeats <= 0;
  const international = (props.country || "India").trim().toLowerCase() !== "india";
  const departureCities = props.departureCities?.filter(Boolean) ?? [];
  const [form, setForm] = useState({ departureCity: international ? departureCities[0] || "" : "Joining Direct", travelStartDate: "", adults: 1, childrenWithBed: 0, childrenWithoutBed: 0, infants: 0, name: session?.user?.name ?? "", email: session?.user?.email ?? "", mobile: "", accepted: false });

  useEffect(() => { if (open) document.body.style.overflow = "hidden"; return () => { document.body.style.overflow = ""; }; }, [open]);

  const travelers = form.adults + form.childrenWithBed + form.childrenWithoutBed + form.infants;
  const total = props.pricePerPerson * travelers;
  const endDate = (() => { if (!form.travelStartDate) return ""; const value = new Date(`${form.travelStartDate}T00:00:00.000Z`); value.setUTCDate(value.getUTCDate() + packageDays - 1); return value.toISOString().slice(0, 10); })();

  function update<K extends keyof typeof form>(key: K, value: (typeof form)[K]) { setForm((current) => ({ ...current, [key]: value })); setCalculated(false); }
  function validate() { if (!form.departureCity.trim()) return "Enter your departure city."; if (!form.travelStartDate) return "Select your date of travel."; if (form.name.trim().length < 2) return "Enter the lead traveler name."; if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)) return "Enter a valid email address."; if (!/^[6-9]\d{9}$/.test(form.mobile)) return "Enter a valid 10-digit mobile number."; if (!form.accepted) return "Accept the booking terms to continue."; if (!props.customDate && travelers > props.availableSeats) return `Only ${props.availableSeats} seats are available.`; return ""; }
  function calculate() { const error = validate(); if (error) return toast.error(error); setCalculated(true); }
  function continueToReview() { const error = validate(); if (error) return toast.error(error); setContinuing(true); const draft: BookingDraft = { tripId: props.tripId, slug: props.slug, partnerSlug: props.partnerSlug, departureCity: form.departureCity.trim(), travelStartDate: form.travelStartDate, travelEndDate: endDate, adults: form.adults, childrenWithBed: form.childrenWithBed, childrenWithoutBed: form.childrenWithoutBed, infants: form.infants, seats: travelers, name: form.name.trim(), email: form.email.trim(), mobile: form.mobile, pricePerPerson: props.pricePerPerson, totalAmount: total }; sessionStorage.setItem("voibee-booking-draft", JSON.stringify(draft)); router.push(`/booking-review?package=${encodeURIComponent(props.slug)}`); }

  return <>
    <div className="sticky top-24 rounded-2xl border border-primary/15 bg-white p-5 shadow-lg shadow-primary/5"><p className="text-sm text-muted-foreground">Starting from</p><p className="mt-1 text-3xl font-extrabold text-slate-950">{formatINR(props.pricePerPerson)} <span className="text-sm font-medium text-muted-foreground">/ person</span></p><p className="mt-3 flex items-center gap-2 text-sm text-muted-foreground"><Calendar className="size-4 text-primary" />{props.customDate ? `${packageDays} days · select your date` : `${formatDate(props.startDate)} – ${formatDate(props.endDate)}`}</p><Button disabled={soldOut} variant="gradient" size="lg" className="mt-5 w-full" onClick={() => setOpen(true)}>{soldOut ? "Sold Out" : "Book Now"}</Button><p className="mt-3 flex items-center justify-center gap-1.5 text-xs text-muted-foreground"><ShieldCheck className="size-3.5 text-success" />Online and offline booking available</p></div>
    {open ? <div className="fixed inset-0 z-[80] flex items-end justify-center bg-slate-950/55 backdrop-blur-sm sm:items-center sm:p-5" role="dialog" aria-modal="true" aria-labelledby="booking-title" onMouseDown={(event) => { if (event.target === event.currentTarget) setOpen(false); }}><div className="max-h-[94vh] w-full max-w-5xl overflow-y-auto rounded-t-3xl bg-white shadow-2xl sm:rounded-3xl"><div className="sticky top-0 z-10 flex items-center justify-between border-b border-border bg-white px-5 py-4 sm:px-7"><div><p className="text-xs font-bold uppercase tracking-wider text-primary">Plan your booking</p><h2 id="booking-title" className="text-xl font-extrabold sm:text-2xl">Traveler and trip details</h2></div><button type="button" onClick={() => setOpen(false)} className="flex size-10 items-center justify-center rounded-full bg-secondary hover:bg-slate-200" aria-label="Close booking form"><X className="size-5" /></button></div>
      <div className="space-y-7 p-5 sm:p-7"><div className="grid gap-5 sm:grid-cols-2"><div><Label htmlFor="departure-city" className="mb-2 block">{international ? "Departure city" : "Departure"} <span className="text-destructive">*</span></Label>{international ? <Select id="departure-city" value={form.departureCity} onChange={(e) => update("departureCity", e.target.value)} className="h-12" required><option value="" disabled>Select departure city</option>{departureCities.map((city) => <option key={city} value={city}>{city}</option>)}</Select> : <div id="departure-city" className="flex h-12 items-center rounded-md border border-input bg-secondary/40 px-3 font-semibold text-slate-700">Joining Direct</div>}{international && !departureCities.length ? <p className="mt-1 text-xs text-destructive">Departure cities are not configured for this package.</p> : null}</div><div><Label htmlFor="travel-date" className="mb-2 block">Date of travel <span className="text-destructive">*</span></Label><Input id="travel-date" type="date" value={form.travelStartDate} min={new Date().toISOString().slice(0, 10)} onChange={(e) => update("travelStartDate", e.target.value)} className="h-12" required /></div></div>
      <div className="border-y border-dashed border-border py-6"><h3 className="mb-5 text-lg font-extrabold">Travelers <span className="text-sm font-normal text-muted-foreground">(maximum 20)</span></h3><div className="grid grid-cols-2 gap-4 lg:grid-cols-4"><Counter label="Adult" hint="12+ years" value={form.adults} min={1} onChange={(value) => update("adults", value)} /><Counter label="Child (with bed)" hint="Below 12 years" value={form.childrenWithBed} onChange={(value) => update("childrenWithBed", value)} /><Counter label="Child (without bed)" hint="Below 12 years" value={form.childrenWithoutBed} onChange={(value) => update("childrenWithoutBed", value)} /><Counter label="Infant" hint="0–2 years" value={form.infants} onChange={(value) => update("infants", value)} /></div></div>
      <div><h3 className="mb-5 text-lg font-extrabold">Contact details <span className="text-sm font-normal text-muted-foreground">(Booking updates will be sent here)</span></h3><div className="grid gap-4 sm:grid-cols-3"><div><Label htmlFor="traveler-name" className="mb-2 block">Full name <span className="text-destructive">*</span></Label><Input id="traveler-name" value={form.name} onChange={(e) => update("name", e.target.value)} className="h-12" /></div><div><Label htmlFor="traveler-mobile" className="mb-2 block">Mobile number <span className="text-destructive">*</span></Label><Input id="traveler-mobile" inputMode="numeric" maxLength={10} value={form.mobile} onChange={(e) => update("mobile", e.target.value.replace(/\D/g, ""))} className="h-12" /></div><div><Label htmlFor="traveler-email" className="mb-2 block">Email <span className="text-destructive">*</span></Label><Input id="traveler-email" type="email" value={form.email} onChange={(e) => update("email", e.target.value)} className="h-12" /></div></div></div>
      <label className="flex cursor-pointer items-start gap-3 text-sm"><input type="checkbox" checked={form.accepted} onChange={(e) => update("accepted", e.target.checked)} className="mt-0.5 size-5 accent-primary" /><span>I accept the <a href="/terms" target="_blank" className="font-semibold text-primary underline">Terms & Conditions</a> and <a href="/privacy" target="_blank" className="font-semibold text-primary underline">Privacy Policy</a>. <span className="text-destructive">*</span></span></label>
      <div className="flex flex-col items-stretch justify-end gap-4 border-t border-border pt-5 sm:flex-row sm:items-center">{!calculated ? <Button type="button" variant="gradient" size="lg" onClick={calculate}>Calculate Price</Button> : <><div className="mr-auto rounded-2xl bg-primary/5 px-5 py-3"><p className="text-xs font-semibold text-muted-foreground">Total for {travelers} traveler{travelers === 1 ? "" : "s"}</p><p className="text-2xl font-extrabold text-primary">{formatINR(total)}</p></div><Button type="button" variant="gradient" size="lg" disabled={continuing} onClick={continueToReview}>{continuing ? <Loader2 className="size-4 animate-spin" /> : <Check className="size-4" />}Continue</Button></>}</div></div></div></div> : null}
  </>;
}
