import { portalCall } from "@/lib/portal-client";
import type * as Contract from "@/types/portal/dashboard";
export const getPartnerByUser = (...args: Parameters<typeof Contract.getPartnerByUser>): ReturnType<typeof Contract.getPartnerByUser> => portalCall("getPartnerByUser", args);
export const getPartnerStats = (...args: Parameters<typeof Contract.getPartnerStats>): ReturnType<typeof Contract.getPartnerStats> => portalCall("getPartnerStats", args);
export const getPartnerEarningsChart = (...args: Parameters<typeof Contract.getPartnerEarningsChart>): ReturnType<typeof Contract.getPartnerEarningsChart> => portalCall("getPartnerEarningsChart", args);
export const getPartnerLinks = (...args: Parameters<typeof Contract.getPartnerLinks>): ReturnType<typeof Contract.getPartnerLinks> => portalCall("getPartnerLinks", args);
export const getPartnerBookings = (...args: Parameters<typeof Contract.getPartnerBookings>): ReturnType<typeof Contract.getPartnerBookings> => portalCall("getPartnerBookings", args);
export const getPartnerCommissions = (...args: Parameters<typeof Contract.getPartnerCommissions>): ReturnType<typeof Contract.getPartnerCommissions> => portalCall("getPartnerCommissions", args);
export const getResellableTrips = (...args: Parameters<typeof Contract.getResellableTrips>): ReturnType<typeof Contract.getResellableTrips> => portalCall("getResellableTrips", args);
export const getTravelerBookings = (...args: Parameters<typeof Contract.getTravelerBookings>): ReturnType<typeof Contract.getTravelerBookings> => portalCall("getTravelerBookings", args);
export const getTravelerWishlist = (...args: Parameters<typeof Contract.getTravelerWishlist>): ReturnType<typeof Contract.getTravelerWishlist> => portalCall("getTravelerWishlist", args);
