import { portalCall } from "@/lib/portal-client";
import type * as Contract from "@/types/portal/data";
export function isIndiaCountry(code?: string) { return (code ?? "IN").toUpperCase() === "IN"; }
export const getActivityTypes = (...args: Parameters<typeof Contract.getActivityTypes>): ReturnType<typeof Contract.getActivityTypes> => portalCall("getActivityTypes", args);
export const getActivities = (...args: Parameters<typeof Contract.getActivities>): ReturnType<typeof Contract.getActivities> => portalCall("getActivities", args);
export const getActivityBySlug = (...args: Parameters<typeof Contract.getActivityBySlug>): ReturnType<typeof Contract.getActivityBySlug> => portalCall("getActivityBySlug", args);
export const getDestinations = (...args: Parameters<typeof Contract.getDestinations>): ReturnType<typeof Contract.getDestinations> => portalCall("getDestinations", args);
export const getHomeDestinations = (...args: Parameters<typeof Contract.getHomeDestinations>): ReturnType<typeof Contract.getHomeDestinations> => portalCall("getHomeDestinations", args);
export const getDestinationLanding = (...args: Parameters<typeof Contract.getDestinationLanding>): ReturnType<typeof Contract.getDestinationLanding> => portalCall("getDestinationLanding", args);
export const getOfferCards = (...args: Parameters<typeof Contract.getOfferCards>): ReturnType<typeof Contract.getOfferCards> => portalCall("getOfferCards", args);
export type { TripFilters } from "@/types/portal/data";
export const getTripCategoryCounts = (...args: Parameters<typeof Contract.getTripCategoryCounts>): ReturnType<typeof Contract.getTripCategoryCounts> => portalCall("getTripCategoryCounts", args);
export const getTrips = (...args: Parameters<typeof Contract.getTrips>): ReturnType<typeof Contract.getTrips> => portalCall("getTrips", args);
export const getFeaturedTrips = (...args: Parameters<typeof Contract.getFeaturedTrips>): ReturnType<typeof Contract.getFeaturedTrips> => portalCall("getFeaturedTrips", args);
export const getTripsByCategory = (...args: Parameters<typeof Contract.getTripsByCategory>): ReturnType<typeof Contract.getTripsByCategory> => portalCall("getTripsByCategory", args);
export const getTripBySlug = (...args: Parameters<typeof Contract.getTripBySlug>): ReturnType<typeof Contract.getTripBySlug> => portalCall("getTripBySlug", args);
export const getRelatedTrips = (...args: Parameters<typeof Contract.getRelatedTrips>): ReturnType<typeof Contract.getRelatedTrips> => portalCall("getRelatedTrips", args);
export const getReviewsForTrip = (...args: Parameters<typeof Contract.getReviewsForTrip>): ReturnType<typeof Contract.getReviewsForTrip> => portalCall("getReviewsForTrip", args);
export const getPartnerBySlug = (...args: Parameters<typeof Contract.getPartnerBySlug>): ReturnType<typeof Contract.getPartnerBySlug> => portalCall("getPartnerBySlug", args);
export const getWhiteLabelTrip = (...args: Parameters<typeof Contract.getWhiteLabelTrip>): ReturnType<typeof Contract.getWhiteLabelTrip> => portalCall("getWhiteLabelTrip", args);
export const getPartnerStorefront = (...args: Parameters<typeof Contract.getPartnerStorefront>): ReturnType<typeof Contract.getPartnerStorefront> => portalCall("getPartnerStorefront", args);
export const trackPartnerTripClick = (...args: Parameters<typeof Contract.trackPartnerTripClick>): ReturnType<typeof Contract.trackPartnerTripClick> => portalCall("trackPartnerTripClick", args);
export const getHomeStats = (...args: Parameters<typeof Contract.getHomeStats>): ReturnType<typeof Contract.getHomeStats> => portalCall("getHomeStats", args);
