"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Pencil, Plus, X, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { CurrencyPrice } from "@/components/currency/currency-price";
import type { ActivityDTO, ActivityTypeDTO } from "@/types";

const lines = (value: string) => value.split("\n").map((item) => item.trim()).filter(Boolean);
const slug = (value: string) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

export function ActivityInventoryManager({ activities, types }: { activities: ActivityDTO[]; types: ActivityTypeDTO[] }) {
  const [typeEditing, setTypeEditing] = useState<ActivityTypeDTO | null | undefined>();
  const [activityEditing, setActivityEditing] = useState<ActivityDTO | null | undefined>();
  return <div className="space-y-8">
    <section className="space-y-4">
      <div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-bold">Activity types</h2><p className="text-sm text-muted-foreground">Categories shown on the public Activities page.</p></div><Button variant="outline" onClick={() => setTypeEditing(null)}><Plus className="size-4" />Add activity type</Button></div>
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{types.map((type) => <Card key={type._id}><CardContent className="p-4"><div className="mb-3 aspect-[16/9] rounded-xl bg-cover bg-center bg-secondary" style={{ backgroundImage: type.image ? `url(${type.image})` : undefined }} /><div className="flex items-start justify-between gap-2"><div><p className="font-bold">{type.name}</p><p className="mt-1 line-clamp-2 text-xs text-muted-foreground">{type.description || "No description"}</p></div><Button size="icon" variant="ghost" onClick={() => setTypeEditing(type)}><Pencil className="size-4" /></Button></div><Badge variant={type.status === "active" ? "success" : "secondary"} className="mt-3">{type.status}</Badge></CardContent></Card>)}</div>
    </section>
    <section className="space-y-4">
      <div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-bold">Activities</h2><p className="text-sm text-muted-foreground">Bookable experiences, prices and detail-page content.</p></div><Button variant="gradient" onClick={() => setActivityEditing(null)}><Plus className="size-4" />Add activity</Button></div>
      <Card><CardContent className="overflow-x-auto p-0">{activities.length ? <table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b text-left text-muted-foreground"><th className="p-4">Activity</th><th className="p-4">Type</th><th className="p-4">Price</th><th className="p-4">Placement</th><th className="p-4">Status</th><th className="p-4 text-right">Action</th></tr></thead><tbody>{activities.map((activity) => { const type = typeof activity.type === "string" ? null : activity.type; return <tr key={activity._id} className="border-b border-border/50"><td className="p-4"><p className="font-bold">{activity.title}</p><p className="text-xs text-muted-foreground">{activity.destination}, {activity.country}</p></td><td className="p-4">{type?.name ?? "—"}</td><td className="p-4 font-bold text-primary"><CurrencyPrice amount={activity.basePrice} /></td><td className="p-4"><div className="flex flex-wrap gap-1">{activity.seasonal ? <Badge variant="warning">Seasonal</Badge> : null}{activity.bestSelling ? <Badge variant="accent">Best-selling</Badge> : null}{activity.featured ? <Badge>Featured</Badge> : null}</div></td><td className="p-4"><Badge variant={activity.status === "active" ? "success" : "secondary"}>{activity.status}</Badge></td><td className="p-4 text-right"><Button size="sm" variant="outline" onClick={() => setActivityEditing(activity)}><Pencil className="size-3.5" />Edit</Button></td></tr>; })}</tbody></table> : <div className="py-12 text-center text-sm text-muted-foreground">No activities configured.</div>}</CardContent></Card>
    </section>
    {typeEditing !== undefined ? <TypeDrawer item={typeEditing ?? undefined} onClose={() => setTypeEditing(undefined)} /> : null}
    {activityEditing !== undefined ? <ActivityDrawer item={activityEditing ?? undefined} types={types} onClose={() => setActivityEditing(undefined)} /> : null}
  </div>;
}

function Drawer({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) { return <div className="fixed inset-0 z-[90]"><button className="absolute inset-0 bg-black/50" onClick={onClose} aria-label="Close" /><aside className="absolute right-0 top-0 flex h-full w-full max-w-2xl flex-col border-l bg-background shadow-2xl"><div className="flex items-center justify-between border-b p-4"><h2 className="text-lg font-bold">{title}</h2><Button variant="ghost" size="icon" onClick={onClose}><X /></Button></div><div className="min-h-0 flex-1 overflow-y-auto p-5">{children}</div></aside></div>; }

function TypeDrawer({ item, onClose }: { item?: ActivityTypeDTO; onClose: () => void }) {
  const router = useRouter(); const [loading, setLoading] = useState(false); const [form, setForm] = useState({ name: item?.name ?? "", slug: item?.slug ?? "", description: item?.description ?? "", image: item?.image ?? "", status: item?.status ?? "active", featured: item?.featured ?? false, sortOrder: item?.sortOrder ?? 0 });
  async function submit(event: React.FormEvent) { event.preventDefault(); setLoading(true); try { const response = await fetch(item ? `/api/admin/activity-types/${item._id}` : "/api/admin/activity-types", { method: item ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, slug: form.slug || slug(form.name), sortOrder: Number(form.sortOrder) }) }); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.message || "Save failed"); toast.success(item ? "Activity type updated" : "Activity type created"); onClose(); router.refresh(); } catch (error) { toast.error((error as Error).message); setLoading(false); } }
  return <Drawer title={item ? "Edit activity type" : "Add activity type"} onClose={onClose}><form onSubmit={submit} className="space-y-4"><Field label="Name"><Input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /></Field><Field label="Slug"><Input value={form.slug} onChange={(e) => setForm({ ...form, slug: e.target.value })} placeholder="Generated from name" /></Field><Field label="Description"><Textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></Field><Field label="Image URL"><Input value={form.image} onChange={(e) => setForm({ ...form, image: e.target.value })} /></Field><div className="grid grid-cols-2 gap-4"><Field label="Status"><Select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as typeof form.status })}><option value="active">Active</option><option value="inactive">Inactive</option></Select></Field><Field label="Sort order"><Input type="number" min={0} value={form.sortOrder} onChange={(e) => setForm({ ...form, sortOrder: Number(e.target.value) })} /></Field></div><label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" checked={form.featured} onChange={(e) => setForm({ ...form, featured: e.target.checked })} />Featured type</label><Save loading={loading} label={item ? "Save type" : "Create type"} /></form></Drawer>;
}

function ActivityDrawer({ item, types, onClose }: { item?: ActivityDTO; types: ActivityTypeDTO[]; onClose: () => void }) {
  const router = useRouter(); const typeId = typeof item?.type === "string" ? item.type : item?.type?._id; const [loading, setLoading] = useState(false); const [form, setForm] = useState({ title: item?.title ?? "", slug: item?.slug ?? "", type: typeId ?? types[0]?._id ?? "", destination: item?.destination ?? "", country: item?.country ?? "India", shortDescription: item?.shortDescription ?? "", description: item?.description ?? "", images: (item?.images ?? []).join("\n"), basePrice: item?.basePrice ?? 0, originalPrice: item?.originalPrice ?? 0, duration: item?.duration ?? "", highlights: (item?.highlights ?? []).join("\n"), inclusions: (item?.inclusions ?? []).join("\n"), exclusions: (item?.exclusions ?? []).join("\n"), importantInfo: (item?.importantInfo ?? []).join("\n"), meetingPoint: item?.meetingPoint ?? "", seasonal: item?.seasonal ?? false, bestSelling: item?.bestSelling ?? false, featured: item?.featured ?? false, status: item?.status ?? "draft" });
  async function submit(event: React.FormEvent) { event.preventDefault(); setLoading(true); const payload = { ...form, slug: form.slug || slug(form.title), basePrice: Number(form.basePrice), originalPrice: Number(form.originalPrice), images: lines(form.images), highlights: lines(form.highlights), inclusions: lines(form.inclusions), exclusions: lines(form.exclusions), importantInfo: lines(form.importantInfo) }; try { const response = await fetch(item ? `/api/admin/activities/${item._id}` : "/api/admin/activities", { method: item ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.message || "Save failed"); toast.success(item ? "Activity updated" : "Activity created"); onClose(); router.refresh(); } catch (error) { toast.error((error as Error).message); setLoading(false); } }
  return <Drawer title={item ? "Edit activity" : "Add activity"} onClose={onClose}><form onSubmit={submit} className="space-y-4"><Field label="Activity name"><Input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} required /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Activity type"><Select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })} required>{types.map((type) => <option key={type._id} value={type._id}>{type.name}</option>)}</Select></Field><Field label="Status"><Select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as typeof form.status })}><option value="draft">Draft</option><option value="active">Active</option><option value="inactive">Inactive</option></Select></Field><Field label="Destination"><Input value={form.destination} onChange={(e) => setForm({ ...form, destination: e.target.value })} required /></Field><Field label="Country"><Input value={form.country} onChange={(e) => setForm({ ...form, country: e.target.value })} /></Field><Field label="Selling price"><Input type="number" min={0} value={form.basePrice} onChange={(e) => setForm({ ...form, basePrice: Number(e.target.value) })} /></Field><Field label="Original price"><Input type="number" min={0} value={form.originalPrice} onChange={(e) => setForm({ ...form, originalPrice: Number(e.target.value) })} /></Field><Field label="Duration"><Input value={form.duration} onChange={(e) => setForm({ ...form, duration: e.target.value })} placeholder="3 hours" /></Field><Field label="Slug"><Input value={form.slug} onChange={(e) => setForm({ ...form, slug: e.target.value })} placeholder="Generated from name" /></Field></div><Field label="Short description"><Textarea value={form.shortDescription} onChange={(e) => setForm({ ...form, shortDescription: e.target.value })} /></Field><Field label="Full description"><Textarea className="min-h-28" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></Field>{(["images", "highlights", "inclusions", "exclusions", "importantInfo"] as const).map((key) => <Field key={key} label={`${key.replace(/([A-Z])/g, " $1")} (one per line)`}><Textarea value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} /></Field>)}<Field label="Meeting point"><Input value={form.meetingPoint} onChange={(e) => setForm({ ...form, meetingPoint: e.target.value })} /></Field><div className="flex flex-wrap gap-5">{(["seasonal", "bestSelling", "featured"] as const).map((key) => <label key={key} className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" checked={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.checked })} />{key === "bestSelling" ? "Best-selling" : key[0].toUpperCase() + key.slice(1)}</label>)}</div><Save loading={loading} label={item ? "Save activity" : "Create activity"} /></form></Drawer>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div><Label className="mb-1.5 block">{label}</Label>{children}</div>; }
function Save({ loading, label }: { loading: boolean; label: string }) { return <div className="sticky bottom-0 -mx-5 -mb-5 flex justify-end border-t bg-background/95 p-4"><Button type="submit" variant="gradient" disabled={loading}>{loading ? <Loader2 className="size-4 animate-spin" /> : null}{label}</Button></div>; }
