import Link from "next/link";
import { UsersRound } from "lucide-react";
import { EmployeeDrawer } from "@/components/admin/employee-drawer";
import { EmployeeRowActions } from "@/components/admin/employee-row-actions";
import { StatusBadge } from "@/components/dashboard/status-badge";
import { Card, CardContent } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { formatDate, formatINR } from "@/lib/utils";
import type { EmployeeDTO } from "@/types";

export function EmployeeSection({ employees, canManage=true, filters }: { employees:EmployeeDTO[]; canManage?:boolean; filters?:React.ReactNode }) {
  return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Employees</h2><p className="text-muted-foreground">{canManage?"Manage team members, salaries and portal access":"Your employee profile"}</p></div>{canManage&&<EmployeeDrawer/>}</div>{filters}
    {employees.length?<Card><CardContent className="overflow-x-auto p-0"><table className={canManage?"w-full min-w-[900px] text-sm":"w-full min-w-[600px] text-sm"}><thead><tr className="border-b text-left text-muted-foreground"><th className="p-4">Employee</th><th className="p-4">Role</th>{canManage&&<th className="p-4">Portal</th>}{canManage&&<th className="p-4">Salary</th>}<th className="p-4">Joined</th><th className="p-4">Status</th>{canManage&&<th className="p-4 text-right">Action</th>}</tr></thead><tbody>{employees.map((employee)=><tr key={employee._id} className="border-b border-border/50 hover:bg-secondary/40"><td className="p-4">{canManage?<Link href={`/admin/hrm/employees/${employee._id}`} className="font-medium text-primary hover:underline">{employee.name}</Link>:<p className="font-medium">{employee.name}</p>}<p className="text-xs text-muted-foreground">{employee.email} · {employee.mobile||"no mobile"}</p></td><td className="p-4"><p>{employee.designation}</p><p className="text-xs text-muted-foreground">{employee.department}</p></td>{canManage&&<td className="p-4"><p className="font-medium">{employee.portalAccess?"Enabled":"No access"}</p><p className="text-xs text-muted-foreground">{employee.portalAccess?`${employee.portalPages?.length||0} pages`:"—"}</p></td>}{canManage&&<td className="p-4 font-medium">{formatINR(employee.salary)}</td>}<td className="p-4">{employee.joinedAt?formatDate(employee.joinedAt):"—"}</td><td className="p-4"><StatusBadge status={employee.status}/></td>{canManage&&<td className="p-4"><EmployeeRowActions employee={employee}/></td>}</tr>)}</tbody></table></CardContent></Card>:<EmptyState icon={UsersRound} title="No employee profile" description={canManage?"Add your first internal team member.":"Your employee profile is not available."} action={canManage?<EmployeeDrawer/>:undefined}/>}</div>;
}
