import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";

function HeaderSkeleton({action=true}:{action?:boolean}){return <div className="flex items-end justify-between gap-4"><div className="space-y-2"><Skeleton className="h-7 w-48"/><Skeleton className="h-4 w-72 max-w-[65vw]"/></div>{action&&<Skeleton className="h-10 w-36 rounded-lg"/>}</div>}
function FilterSkeleton({status=true}:{status?:boolean}){return <div className="flex flex-col gap-2 rounded-xl border bg-card p-3 sm:flex-row"><Skeleton className="h-10 flex-1"/>{status&&<Skeleton className="h-10 sm:w-48"/>}<Skeleton className="h-10 w-24"/></div>}
function TableSkeleton({columns=6,rows=6}:{columns?:number;rows?:number}){return <Card><CardContent className="p-0"><div className="flex gap-5 border-b p-4">{Array.from({length:columns},(_,index)=><Skeleton key={index} className="h-4 flex-1"/>)}</div>{Array.from({length:rows},(_,row)=><div key={row} className="flex items-center gap-5 border-b p-4 last:border-0"><div className="flex-1 space-y-2"><Skeleton className="h-4 w-3/4"/><Skeleton className="h-3 w-1/2"/></div>{Array.from({length:Math.max(1,columns-2)},(_,column)=><Skeleton key={column} className="hidden h-4 flex-1 sm:block"/>)}<Skeleton className="h-7 w-20 rounded-full"/></div>)}</CardContent></Card>}

export function HrmTablePageSkeleton({statusFilter=true,columns=6}:{statusFilter?:boolean;columns?:number}){return <div className="space-y-5" role="status" aria-label="Loading records"><HeaderSkeleton/><FilterSkeleton status={statusFilter}/><TableSkeleton columns={columns}/><span className="sr-only">Loading…</span></div>}

export function HrmDashboardSkeleton(){return <div className="space-y-6" role="status" aria-label="Loading HRM dashboard"><HeaderSkeleton action={false}/><Card><CardContent className="flex flex-col items-center gap-4 p-6"><Skeleton className="h-4 w-32"/><Skeleton className="h-12 w-56"/><Skeleton className="h-11 w-36"/></CardContent></Card><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Array.from({length:4},(_,index)=><Card key={index}><CardContent className="space-y-3 p-5"><Skeleton className="h-4 w-28"/><Skeleton className="h-8 w-20"/><Skeleton className="h-3 w-24"/></CardContent></Card>)}</div><div className="grid gap-5 xl:grid-cols-2">{Array.from({length:2},(_,column)=><Card key={column}><CardContent className="space-y-3 p-5"><Skeleton className="h-6 w-40"/>{Array.from({length:4},(__,row)=><Skeleton key={row} className="h-14 w-full rounded-lg"/>)}</CardContent></Card>)}</div></div>}

export function AttendanceCalendarSkeleton(){return <div className="space-y-6" role="status" aria-label="Loading attendance calendar"><HeaderSkeleton/><Card><CardContent className="p-5"><div className="mb-4 flex items-center justify-between"><Skeleton className="size-10"/><Skeleton className="h-6 w-40"/><Skeleton className="size-10"/></div><div className="grid grid-cols-7 border-l border-t">{Array.from({length:42},(_,index)=><div key={index} className="min-h-24 border-b border-r p-2 sm:min-h-32"><Skeleton className="size-5"/>{index>6&&<><Skeleton className="mt-4 h-3 w-3/4"/><Skeleton className="mt-2 h-3 w-1/2"/></>}</div>)}</div></CardContent></Card></div>}

export function EmployeeProfileSkeleton(){return <div className="space-y-6" role="status" aria-label="Loading employee profile"><Skeleton className="h-8 w-28"/><Card><CardContent className="space-y-5 p-6"><div className="flex items-center gap-3"><Skeleton className="size-12 rounded-full"/><div className="space-y-2"><Skeleton className="h-7 w-52"/><Skeleton className="h-4 w-40"/></div></div><div className="grid gap-4 sm:grid-cols-3">{Array.from({length:6},(_,index)=><div className="space-y-2" key={index}><Skeleton className="h-3 w-16"/><Skeleton className="h-4 w-32"/></div>)}</div></CardContent></Card><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Array.from({length:4},(_,index)=><Skeleton key={index} className="h-24 rounded-xl"/>)}</div>{Array.from({length:3},(_,index)=><TableSkeleton key={index} columns={5} rows={3}/>)}</div>}
