import { BedDouble, Truck } from "lucide-react";
import { SupplierDrawer } from "@/components/admin/supplier-drawer";
import { StatusBadge } from "@/components/dashboard/status-badge";
import { Card, CardContent } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import type { SupplierDTO } from "@/types";

export function InventorySuppliers({ suppliers, supplierOptions, kind }: { suppliers: SupplierDTO[]; supplierOptions: SupplierDTO[]; kind: "Hotel" | "Transport" }) {
  const hotel = kind === "Hotel"; const label = hotel ? "Hotels" : "Vehicles"; const Icon = hotel ? BedDouble : Truck;
  return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">{label}</h2><p className="text-sm text-muted-foreground">{suppliers.length} active and inactive {label.toLowerCase()} suppliers</p></div><SupplierDrawer defaultType={kind} supplierOptions={supplierOptions} requireSupplierSelection /></div>{suppliers.length ? <Card><CardContent className="overflow-x-auto p-0"><table className="w-full text-sm"><thead><tr className="border-b text-left text-muted-foreground"><th className="p-4">Supplier</th><th className="p-4">Contact</th><th className="p-4">Location</th><th className="p-4">Commission</th><th className="p-4">Status</th><th className="p-4 text-right">Action</th></tr></thead><tbody>{suppliers.map((supplier) => <tr key={supplier._id} className="border-b border-border/50"><td className="p-4"><p className="font-medium">{supplier.companyName}</p><p className="text-xs text-muted-foreground">{supplier.contactName || "No contact"}</p></td><td className="p-4"><p>{supplier.phone}</p><p className="text-xs text-muted-foreground">{supplier.email || "—"}</p></td><td className="p-4">{[supplier.city, supplier.country].filter(Boolean).join(", ")}</td><td className="p-4">{supplier.commissionRate}%</td><td className="p-4"><StatusBadge status={supplier.status} /></td><td className="p-4 text-right"><SupplierDrawer supplier={supplier} defaultType={kind} supplierOptions={supplierOptions} requireSupplierSelection /></td></tr>)}</tbody></table></CardContent></Card> : <EmptyState icon={Icon} title={`No ${label.toLowerCase()} configured`} action={<SupplierDrawer defaultType={kind} supplierOptions={supplierOptions} requireSupplierSelection />} />}</div>;
}
