"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Loader2, Pencil, Plus, X } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { VISA_STATUSES } from "@/lib/constants";
import type { LeadDTO, UserDTO, VisaApplicationDTO } from "@/types";

const Mark = () => <span className="text-destructive">*</span>;
const dateValue = (value?: string | null) => value?.slice(0, 10) ?? "";

const refId = (value: unknown) => typeof value === "string" ? value : (value as { _id?: string } | null)?._id ?? "";

export function VisaDrawer({ visa, leads, customers }: { visa?: VisaApplicationDTO; leads: LeadDTO[]; customers: UserDTO[] }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(false);
  const [form, setForm] = useState({ leadId: refId(visa?.lead), customerId: refId(visa?.customer), passportNumber: visa?.passportNumber ?? "", destinationCountry: visa?.destinationCountry ?? "", visaType: visa?.visaType ?? "Tourist", status: visa?.status ?? "documents_pending", submittedAt: dateValue(visa?.submittedAt), expectedAt: dateValue(visa?.expectedAt), completedAt: dateValue(visa?.completedAt), bookingNumber: visa?.bookingNumber ?? "", assignedTo: visa?.assignedTo ?? "", notes: visa?.notes ?? "" });
  const set = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  async function submit(event: React.FormEvent) { event.preventDefault(); setLoading(true); try { const response = await fetch(visa ? `/api/admin/visas/${visa._id}` : "/api/admin/visas", { method: visa ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.message || "Unable to save visa application"); toast.success(visa ? "Visa tracking updated" : "Visa application added"); setOpen(false); router.refresh(); } catch (error) { toast.error((error as Error).message); setLoading(false); } }
  return <>{visa ? <Button variant="ghost" size="icon" onClick={() => setOpen(true)} aria-label={`Edit ${visa.visaNumber}`}><Pencil className="size-4" /></Button> : <Button variant="gradient" onClick={() => setOpen(true)}><Plus className="size-4" />Add Visa Case</Button>}{open ? <div className="fixed inset-0 z-[80]"><button className="absolute inset-0 bg-black/45" onClick={() => setOpen(false)} aria-label="Close visa form" /><aside role="dialog" aria-modal="true" className="absolute right-0 top-0 flex h-full w-full max-w-2xl flex-col border-l border-border bg-background shadow-2xl"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="text-lg font-bold">{visa ? "Edit Visa Case" : "Add Visa Case"}</h2><p className="text-sm text-muted-foreground">{visa?.visaNumber ?? "Track an applicant from documents to completion"}</p></div><Button variant="ghost" size="icon" onClick={() => setOpen(false)}><X /></Button></div><form onSubmit={submit} className="flex min-h-0 flex-1 flex-col"><div className="grid flex-1 gap-4 overflow-y-auto p-5 sm:grid-cols-2">
    <div className="sm:col-span-2"><Label className="mb-1.5 block">Customer <Mark /></Label><Select required={!form.leadId} value={form.customerId} onChange={(e) => setForm((current) => ({ ...current, customerId: e.target.value, leadId: e.target.value ? "" : current.leadId }))}><option value="">Select customer</option>{customers.map((customer) => <option key={customer._id} value={customer._id}>{customer.name} — {customer.mobile || customer.email}</option>)}</Select></div><div className="sm:col-span-2"><Label className="mb-1.5 block">Or lead <Mark /></Label><Select required={!form.customerId} value={form.leadId} onChange={(e) => setForm((current) => ({ ...current, leadId: e.target.value, customerId: e.target.value ? "" : current.customerId }))}><option value="">Select lead</option>{leads.map((lead) => <option key={lead._id} value={lead._id}>{lead.leadNumber} — {lead.customerName}</option>)}</Select></div>
    <div><Label className="mb-1.5 block">Passport number <Mark /></Label><Input required value={form.passportNumber} onChange={(e) => set("passportNumber", e.target.value.toUpperCase())} /></div><div><Label className="mb-1.5 block">Destination country <Mark /></Label><Input required value={form.destinationCountry} onChange={(e) => set("destinationCountry", e.target.value)} /></div><div><Label className="mb-1.5 block">Visa type <Mark /></Label><Input required value={form.visaType} onChange={(e) => set("visaType", e.target.value)} /></div><div><Label className="mb-1.5 block">Status <Mark /></Label><Select value={form.status} onChange={(e) => set("status", e.target.value)}>{VISA_STATUSES.map((status) => <option key={status} value={status}>{status.replaceAll("_", " ")}</option>)}</Select></div>
    <div><Label className="mb-1.5 block">Submitted date</Label><Input type="date" value={form.submittedAt} onChange={(e) => set("submittedAt", e.target.value)} /></div><div><Label className="mb-1.5 block">Expected date</Label><Input type="date" value={form.expectedAt} onChange={(e) => set("expectedAt", e.target.value)} /></div><div><Label className="mb-1.5 block">Completed date</Label><Input type="date" value={form.completedAt} onChange={(e) => set("completedAt", e.target.value)} /></div><div><Label className="mb-1.5 block">Booking number</Label><Input value={form.bookingNumber} onChange={(e) => set("bookingNumber", e.target.value)} /></div><div className="sm:col-span-2"><Label className="mb-1.5 block">Assigned to</Label><Input value={form.assignedTo} onChange={(e) => set("assignedTo", e.target.value)} /></div><div className="sm:col-span-2"><Label className="mb-1.5 block">Notes</Label><Textarea className="min-h-24" value={form.notes} onChange={(e) => set("notes", e.target.value)} /></div>
  </div><div className="flex justify-end gap-2 border-t p-4"><Button type="button" variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit" variant="gradient" disabled={loading}>{loading ? <Loader2 className="size-4 animate-spin" /> : null}Save</Button></div></form></aside></div> : null}</>;
}
